const bcrypt = require('bcryptjs');

const DEFAULT_PASSWORD = 'password123';
const DEFAULT_PASSWORD_HASH = bcrypt.hashSync(DEFAULT_PASSWORD, 10);

const seedHospitals = [
  {
    id: 'hosp-apollo-greams',
    registration_id: 'REG-HOSP-APOLLO-0842',
    name: 'Apollo Greams Trauma Hub',
    code: 'AP-HSP-842-TN',
    address: '21 Greams Lane, Off Greams Road, Thousand Lights',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600006',
    geoLat: 13.0604,
    geoLng: 80.2496,
    departments: ['Cardiology', 'Emergency & Trauma', 'Neurology', 'Orthopedics', 'ICU & Critical Care', 'Pharmacy'],
    contactNumbers: { er: '+91 44 2829 0200', helpline: '1066', ambulance: '108' },
    icuBedsTotal: 50,
    icuBedsOccupied: 46,
    wardBedsTotal: 400,
    wardBedsOccupied: 336,
    status: 'ACTIVE'
  },
  {
    id: 'HOSP-1',
    registration_id: 'REG-HOSP-AIIMS-1001',
    name: 'AIIMS New Delhi Trauma Center',
    code: 'AIIMS-TC-01',
    address: 'Ansari Nagar',
    city: 'New Delhi',
    state: 'Delhi',
    pinCode: '110029',
    geoLat: 28.5672,
    geoLng: 77.2100,
    departments: ['Polytrauma', 'Neurotrauma', 'Hyperbaric O2'],
    contactNumbers: { er: '+91 11 2658 8500', helpline: '104', ambulance: '108' },
    icuBedsTotal: 20,
    icuBedsOccupied: 6,
    wardBedsTotal: 100,
    wardBedsOccupied: 58,
    status: 'ACTIVE'
  },
  {
    id: 'HOSP-2',
    registration_id: 'REG-HOSP-FORTIS-0002',
    name: 'Fortis Malar Hospital',
    code: 'FORTIS-MLR-02',
    address: 'Adyar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600020',
    geoLat: 13.0067,
    geoLng: 80.2570,
    departments: ['Cardiothoracic', 'ECMO Support', 'Burns'],
    contactNumbers: { er: '+91 44 4289 2222', helpline: '1066', ambulance: '108' },
    icuBedsTotal: 15,
    icuBedsOccupied: 7,
    wardBedsTotal: 80,
    wardBedsOccupied: 58,
    status: 'ACTIVE'
  },
  {
    id: 'HOSP-3',
    registration_id: 'REG-HOSP-STANLEY-0003',
    name: 'Stanley Medical College & Hospital',
    code: 'STANLEY-MCH-03',
    address: 'Royapuram',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600001',
    geoLat: 13.1075,
    geoLng: 80.2928,
    departments: ['Micro-Reconstructive', 'Toxicological Emergency'],
    contactNumbers: { er: '+91 44 2528 1351', helpline: '104', ambulance: '108' },
    icuBedsTotal: 25,
    icuBedsOccupied: 6,
    wardBedsTotal: 150,
    wardBedsOccupied: 90,
    status: 'ACTIVE'
  },
  {
    id: 'HOSP-4',
    registration_id: 'REG-HOSP-MANIPAL-0004',
    name: 'Manipal Hospital Old Airport Road',
    code: 'MANIPAL-BLR-04',
    address: 'HAL Airport Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    pinCode: '560017',
    geoLat: 12.9592,
    geoLng: 77.6534,
    departments: ['Organ Retrieval', 'Interventional Radiology', 'Emergency & Trauma'],
    contactNumbers: { er: '+91 80 2502 4444', helpline: '1066', ambulance: '108' },
    icuBedsTotal: 45,
    icuBedsOccupied: 34,
    wardBedsTotal: 420,
    wardBedsOccupied: 355,
    status: 'ACTIVE'
  },
  {
    id: 'HOSP-5',
    registration_id: 'REG-HOSP-KAUVERY-0005',
    name: 'Kauvery Hospital Main Facility',
    code: 'KAUVERY-ALW-05',
    address: '199 Luz Church Road, Alwarpet',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600004',
    geoLat: 13.0368,
    geoLng: 80.2544,
    departments: ['Cardiology', 'Emergency Medicine', 'Neurosciences', 'Geriatrics'],
    contactNumbers: { er: '+91 44 4000 6000', helpline: '1066', ambulance: '108' },
    icuBedsTotal: 28,
    icuBedsOccupied: 22,
    wardBedsTotal: 220,
    wardBedsOccupied: 182,
    status: 'ACTIVE'
  },
  {
    id: 'HOSP-6',
    registration_id: 'REG-HOSP-MGM-0006',
    name: 'MGM Healthcare Super-Specialty',
    code: 'MGM-AMI-06',
    address: '72 Nelson Manickam Road, Aminjikarai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600029',
    geoLat: 13.0732,
    geoLng: 80.2173,
    departments: ['Heart & Lung Transplant', 'Emergency & Trauma', 'Critical Care', 'ECMO Hub'],
    contactNumbers: { er: '+91 44 4524 2424', helpline: '1066', ambulance: '108' },
    icuBedsTotal: 40,
    icuBedsOccupied: 29,
    wardBedsTotal: 400,
    wardBedsOccupied: 328,
    status: 'ACTIVE'
  },
  {
    id: 'HOSP-7',
    registration_id: 'REG-HOSP-GLOBAL-0007',
    name: 'Gleneagles Global Health City',
    code: 'GLEN-PRM-07',
    address: '439 Cheran Nagar, Perumbakkam',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pinCode: '600100',
    geoLat: 12.9056,
    geoLng: 80.2014,
    departments: ['HPB Surgery & Liver Transplant', 'Trauma Resuscitation', 'Pulmonology'],
    contactNumbers: { er: '+91 44 4477 7000', helpline: '1066', ambulance: '108' },
    icuBedsTotal: 32,
    icuBedsOccupied: 26,
    wardBedsTotal: 350,
    wardBedsOccupied: 286,
    status: 'ACTIVE'
  },
  {
    id: 'HOSP-8',
    registration_id: 'REG-HOSP-CMC-0008',
    name: 'Christian Medical College (CMC) Trauma Center',
    code: 'CMC-VEL-08',
    address: 'Ida Scudder Road',
    city: 'Vellore',
    state: 'Tamil Nadu',
    pinCode: '632004',
    geoLat: 12.9250,
    geoLng: 79.1350,
    departments: ['Trauma Surgery', 'Intensive Care Unit', 'Hyperbaric Medicine', 'Blood Bank'],
    contactNumbers: { er: '+91 416 228 1000', helpline: '104', ambulance: '108' },
    icuBedsTotal: 60,
    icuBedsOccupied: 46,
    wardBedsTotal: 750,
    wardBedsOccupied: 640,
    status: 'ACTIVE'
  },
  {
    id: 'HOSP-9',
    registration_id: 'REG-HOSP-MAX-0009',
    name: 'Max Super Speciality Hospital Saket',
    code: 'MAX-SKT-09',
    address: '1, 2 Press Enclave Marg, Saket',
    city: 'New Delhi',
    state: 'Delhi',
    pinCode: '110017',
    geoLat: 28.5284,
    geoLng: 77.2126,
    departments: ['Emergency Trauma Center', 'Cardiac Sciences', 'Neurosciences', 'Robotic Surgery'],
    contactNumbers: { er: '+91 11 2651 5050', helpline: '1066', ambulance: '108' },
    icuBedsTotal: 38,
    icuBedsOccupied: 31,
    wardBedsTotal: 350,
    wardBedsOccupied: 302,
    status: 'ACTIVE'
  },
  {
    id: 'HOSP-10',
    registration_id: 'REG-HOSP-APOLLO-HYD-0010',
    name: 'Apollo Hospitals Jubilee Hills',
    code: 'AP-HYD-10',
    address: 'Road No. 72, Film Nagar, Jubilee Hills',
    city: 'Hyderabad',
    state: 'Telangana',
    pinCode: '500033',
    geoLat: 17.4173,
    geoLng: 78.4116,
    departments: ['Emergency & Golden Hour Trauma', 'Cardiothoracic', 'Critical Care', 'Stroke Care'],
    contactNumbers: { er: '+91 40 2360 7777', helpline: '1066', ambulance: '108' },
    icuBedsTotal: 42,
    icuBedsOccupied: 33,
    wardBedsTotal: 380,
    wardBedsOccupied: 322,
    status: 'ACTIVE'
  }
];

const HOSPITAL_SCHEMA_FIELDS = [
  { field: 'hospital_id', type: 'UUID / BIGINT', purpose: 'Unique hospital ID' },
  { field: 'hospital_name', type: 'VARCHAR', purpose: 'Official hospital name' },
  { field: 'hospital_type', type: 'VARCHAR', purpose: 'Government / Private / Trust' },
  { field: 'registration_number', type: 'VARCHAR', purpose: 'Hospital registration/license number' },
  { field: 'contact_number', type: 'VARCHAR', purpose: 'Main hospital contact' },
  { field: 'email', type: 'VARCHAR', purpose: 'Official hospital email' },
  { field: 'website', type: 'VARCHAR', purpose: 'Hospital website' },
  { field: 'address', type: 'TEXT', purpose: 'Complete address' },
  { field: 'city', type: 'VARCHAR', purpose: 'City' },
  { field: 'district', type: 'VARCHAR', purpose: 'District' },
  { field: 'state', type: 'VARCHAR', purpose: 'State' },
  { field: 'pincode', type: 'VARCHAR', purpose: 'PIN code' },
  { field: 'latitude', type: 'DECIMAL', purpose: 'GIS location' },
  { field: 'longitude', type: 'DECIMAL', purpose: 'GIS location' },
  { field: 'total_beds', type: 'INTEGER', purpose: 'Total bed capacity' },
  { field: 'available_beds', type: 'INTEGER', purpose: 'Currently available beds' },
  { field: 'icu_beds', type: 'INTEGER', purpose: 'ICU capacity' },
  { field: 'icu_available', type: 'INTEGER', purpose: 'Available ICU beds' },
  { field: 'emergency_beds', type: 'INTEGER', purpose: 'Emergency beds' },
  { field: 'emergency_available', type: 'INTEGER', purpose: 'Available emergency beds' },
  { field: 'general_beds', type: 'INTEGER', purpose: 'General ward beds' },
  { field: 'private_beds', type: 'INTEGER', purpose: 'Private-room beds' },
  { field: 'ambulance_count', type: 'INTEGER', purpose: 'Available ambulances' },
  { field: 'blood_bank_available', type: 'BOOLEAN', purpose: 'Blood bank availability' },
  { field: 'pharmacy_available', type: 'BOOLEAN', purpose: 'Pharmacy availability' },
  { field: 'diagnostic_available', type: 'BOOLEAN', purpose: 'Diagnostic/lab facility' },
  { field: 'operation_theatre_count', type: 'INTEGER', purpose: 'Number of OTs' },
  { field: 'ventilator_count', type: 'INTEGER', purpose: 'Total ventilators' },
  { field: 'oxygen_beds', type: 'INTEGER', purpose: 'Oxygen-supported beds' },
  { field: 'specialities', type: 'JSON / TEXT', purpose: 'Cardiology, Neurology, etc.' },
  { field: 'services', type: 'JSON / TEXT', purpose: 'Emergency, OPD, IPD, Lab, etc.' },
  { field: 'opening_time', type: 'TIME', purpose: 'Regular opening time' },
  { field: 'closing_time', type: 'TIME', purpose: 'Regular closing time' },
  { field: 'emergency_24x7', type: 'BOOLEAN', purpose: '24×7 emergency availability' },
  { field: 'admin_name', type: 'VARCHAR', purpose: 'Hospital administrator' },
  { field: 'admin_phone', type: 'VARCHAR', purpose: 'Administrator contact' },
  { field: 'status', type: 'VARCHAR', purpose: 'Pending / Approved / Suspended' },
  { field: 'created_at', type: 'TIMESTAMP', purpose: 'Registration timestamp' },
  { field: 'updated_at', type: 'TIMESTAMP', purpose: 'Last update' }
];

const seedHospitalSchemaRecords = [
  {
    hospital_id: 'hosp-apollo-greams',
    registration_id: 'REG-HOSP-APOLLO-0842',
    hospital_name: 'Apollo Greams Trauma Hub',
    hospital_type: 'Private',
    registration_number: 'HSP-REG-2210-TN',
    contact_number: '+91 44 2829 0200',
    email: 'admin@apollogreams.org',
    website: 'https://apollohospitals.com/greams',
    address: '21 Greams Lane, Off Greams Road, Thousand Lights',
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600006',
    latitude: 13.0604,
    longitude: 80.2496,
    total_beds: 450,
    available_beds: 68,
    icu_beds: 50,
    icu_available: 4,
    emergency_beds: 12,
    emergency_available: 3,
    general_beds: 240,
    private_beds: 148,
    ambulance_count: 6,
    blood_bank_available: true,
    pharmacy_available: true,
    diagnostic_available: true,
    operation_theatre_count: 14,
    ventilator_count: 18,
    oxygen_beds: 140,
    specialities: ['Cardiology', 'Emergency & Trauma', 'Neurology', 'Orthopedics', 'ICU & Critical Care', 'Nephrology', 'General Surgery', 'Pediatrics'],
    services: ['24x7 Emergency Care', 'OPD Consultations', 'IPD Ward Inpatient', 'Advanced Pathology & Imaging', 'Blood Bank & Transfusion', '24x7 Pharmacy', 'ALS Ambulance Fleet', 'Tele-ICU Grid'],
    opening_time: '00:00',
    closing_time: '23:59',
    emergency_24x7: true,
    admin_name: 'Dr. R. K. Nambiar',
    admin_phone: '+91 94440 28290',
    status: 'Approved',
    created_at: '2025-01-15T09:30:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    hospital_id: 'HOSP-1',
    registration_id: 'REG-HOSP-AIIMS-1001',
    hospital_name: 'AIIMS New Delhi Trauma Center',
    hospital_type: 'Government',
    registration_number: 'AIIMS-REG-1001-DL',
    contact_number: '+91 11 2658 8500',
    email: 'director@aiims.edu',
    website: 'https://www.aiims.edu',
    address: 'Ansari Nagar, Ring Road',
    city: 'New Delhi',
    district: 'New Delhi',
    state: 'Delhi',
    pincode: '110029',
    latitude: 28.5672,
    longitude: 77.2100,
    total_beds: 600,
    available_beds: 88,
    icu_beds: 50,
    icu_available: 14,
    emergency_beds: 30,
    emergency_available: 8,
    general_beds: 380,
    private_beds: 140,
    ambulance_count: 10,
    blood_bank_available: true,
    pharmacy_available: true,
    diagnostic_available: true,
    operation_theatre_count: 18,
    ventilator_count: 38,
    oxygen_beds: 240,
    specialities: ['Polytrauma', 'Neurotrauma', 'Hyperbaric O2', 'Critical Care', 'Burn Triage'],
    services: ['Emergency 24x7', 'OPD', 'IPD', 'Diagnostic Lab', 'Blood Bank', 'Helipad'],
    opening_time: '00:00',
    closing_time: '23:59',
    emergency_24x7: true,
    admin_name: 'Dr. Arvind Mehra',
    admin_phone: '+91 98112 44301',
    status: 'Approved',
    created_at: '2025-02-10T10:00:00.000Z',
    updated_at: '2026-03-20T14:30:00.000Z'
  },
  {
    hospital_id: 'HOSP-2',
    registration_id: 'REG-HOSP-FORTIS-0002',
    hospital_name: 'Fortis Malar Hospital',
    hospital_type: 'Private',
    registration_number: 'HSP-REG-2211-TN',
    contact_number: '+91 44 4289 2222',
    email: 'contactus.malar@fortishealthcare.com',
    website: 'https://fortishealthcare.com/malar',
    address: 'No. 52, 1st Main Road, Gandhi Nagar, Adyar',
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600020',
    latitude: 13.0067,
    longitude: 80.2570,
    total_beds: 180,
    available_beds: 45,
    icu_beds: 15,
    icu_available: 8,
    emergency_beds: 10,
    emergency_available: 4,
    general_beds: 110,
    private_beds: 45,
    ambulance_count: 4,
    blood_bank_available: true,
    pharmacy_available: true,
    diagnostic_available: true,
    operation_theatre_count: 6,
    ventilator_count: 12,
    oxygen_beds: 60,
    specialities: ['Cardiothoracic', 'ECMO Support', 'Burns', 'Critical Care'],
    services: ['24x7 Emergency Care', 'Cardiac ICU', 'Pathology Lab', 'Ambulance'],
    opening_time: '00:00',
    closing_time: '23:59',
    emergency_24x7: true,
    admin_name: 'Dr. Rajesh Nair',
    admin_phone: '+91 98440 33890',
    status: 'Approved',
    created_at: '2025-01-20T10:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    hospital_id: 'HOSP-3',
    registration_id: 'REG-HOSP-STANLEY-0003',
    hospital_name: 'Stanley Medical College & Government Trauma Center',
    hospital_type: 'Government',
    registration_number: 'HSP-REG-STAN-003',
    contact_number: '+91 44 2528 1351',
    email: 'dean.stanley@tn.gov.in',
    website: 'https://stanleymch.tn.gov.in',
    address: '1 Old Jail Road, Royapuram',
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600001',
    latitude: 13.1075,
    longitude: 80.2928,
    total_beds: 550,
    available_beds: 120,
    icu_beds: 35,
    icu_available: 19,
    emergency_beds: 20,
    emergency_available: 9,
    general_beds: 420,
    private_beds: 75,
    ambulance_count: 8,
    blood_bank_available: true,
    pharmacy_available: true,
    diagnostic_available: true,
    operation_theatre_count: 12,
    ventilator_count: 28,
    oxygen_beds: 210,
    specialities: ['Micro-Reconstructive Surgery', 'Toxicological Emergency', 'Trauma Bay', 'Plastic Surgery'],
    services: ['24x7 State Trauma Care', 'Free OPD', 'Central Blood Bank', 'Disaster Bay'],
    opening_time: '00:00',
    closing_time: '23:59',
    emergency_24x7: true,
    admin_name: 'Dr. S. Thirunavukarasu',
    admin_phone: '+91 94441 55660',
    status: 'Approved',
    created_at: '2025-01-05T10:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    hospital_id: 'HOSP-4',
    registration_id: 'REG-HOSP-MANIPAL-0004',
    hospital_name: 'Manipal Hospital Old Airport Road',
    hospital_type: 'Private',
    registration_number: 'HSP-REG-MANI-004',
    contact_number: '+91 80 2502 4444',
    email: 'info@manipalhospitals.com',
    website: 'https://manipalhospitals.com',
    address: '98 HAL Old Airport Road, Kodihalli',
    city: 'Bengaluru',
    district: 'Bengaluru Urban',
    state: 'Karnataka',
    pincode: '560017',
    latitude: 12.9592,
    longitude: 77.6534,
    total_beds: 420,
    available_beds: 65,
    icu_beds: 45,
    icu_available: 11,
    emergency_beds: 16,
    emergency_available: 5,
    general_beds: 260,
    private_beds: 99,
    ambulance_count: 6,
    blood_bank_available: true,
    pharmacy_available: true,
    diagnostic_available: true,
    operation_theatre_count: 14,
    ventilator_count: 22,
    oxygen_beds: 150,
    specialities: ['Organ Retrieval', 'Interventional Radiology', 'Cardiology', 'Pediatric ICU'],
    services: ['24x7 Emergency', 'Transplant Center', 'Comprehensive Cancer Care'],
    opening_time: '00:00',
    closing_time: '23:59',
    emergency_24x7: true,
    admin_name: 'Dr. Shalini Deshmukh',
    admin_phone: '+91 98801 77210',
    status: 'Approved',
    created_at: '2025-01-18T10:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    hospital_id: 'HOSP-5',
    registration_id: 'REG-HOSP-KAUVERY-0005',
    hospital_name: 'Kauvery Hospital Main Facility',
    hospital_type: 'Private',
    registration_number: 'HSP-REG-KAUV-005',
    contact_number: '+91 44 4000 6000',
    email: 'info@kauveryhospital.com',
    website: 'https://kauveryhospital.com',
    address: '199 Luz Church Road, Mylapore / Alwarpet',
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600004',
    latitude: 13.0368,
    longitude: 80.2544,
    total_beds: 220,
    available_beds: 38,
    icu_beds: 28,
    icu_available: 6,
    emergency_beds: 8,
    emergency_available: 3,
    general_beds: 130,
    private_beds: 54,
    ambulance_count: 5,
    blood_bank_available: true,
    pharmacy_available: true,
    diagnostic_available: true,
    operation_theatre_count: 8,
    ventilator_count: 16,
    oxygen_beds: 75,
    specialities: ['Cardiology', 'Emergency Medicine', 'Neurosciences', 'Geriatrics'],
    services: ['24x7 Emergency Care', 'Rapid Cath Lab', 'Pharmacy 24x7'],
    opening_time: '00:00',
    closing_time: '23:59',
    emergency_24x7: true,
    admin_name: 'Dr. Aravindan Selvaraj',
    admin_phone: '+91 98409 12345',
    status: 'Approved',
    created_at: '2025-02-01T10:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    hospital_id: 'HOSP-6',
    registration_id: 'REG-HOSP-MGM-0006',
    hospital_name: 'MGM Healthcare Super-Specialty',
    hospital_type: 'Private',
    registration_number: 'HSP-REG-MGM-006',
    contact_number: '+91 44 4524 2424',
    email: 'care@mgmhealthcare.in',
    website: 'https://mgmhealthcare.in',
    address: '72 Nelson Manickam Road, Aminjikarai',
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600029',
    latitude: 13.0732,
    longitude: 80.2173,
    total_beds: 400,
    available_beds: 72,
    icu_beds: 40,
    icu_available: 11,
    emergency_beds: 14,
    emergency_available: 5,
    general_beds: 240,
    private_beds: 106,
    ambulance_count: 7,
    blood_bank_available: true,
    pharmacy_available: true,
    diagnostic_available: true,
    operation_theatre_count: 16,
    ventilator_count: 24,
    oxygen_beds: 130,
    specialities: ['Heart & Lung Transplant', 'Emergency & Trauma', 'Critical Care', 'ECMO Hub'],
    services: ['24x7 Trauma Resuscitation', 'Green Corridor Organ Transport', 'ICU Grid'],
    opening_time: '00:00',
    closing_time: '23:59',
    emergency_24x7: true,
    admin_name: 'Dr. Prashanth Rajagopalan',
    admin_phone: '+91 98410 44524',
    status: 'Approved',
    created_at: '2025-02-15T10:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    hospital_id: 'HOSP-7',
    registration_id: 'REG-HOSP-GLOBAL-0007',
    hospital_name: 'Gleneagles Global Health City',
    hospital_type: 'Private',
    registration_number: 'HSP-REG-GLEN-007',
    contact_number: '+91 44 4477 7000',
    email: 'info.chennai@gleneagles.com',
    website: 'https://gleneagles.com',
    address: '439 Cheran Nagar, Perumbakkam',
    city: 'Chennai',
    district: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600100',
    latitude: 12.9056,
    longitude: 80.2014,
    total_beds: 350,
    available_beds: 64,
    icu_beds: 32,
    icu_available: 6,
    emergency_beds: 12,
    emergency_available: 4,
    general_beds: 220,
    private_beds: 86,
    ambulance_count: 6,
    blood_bank_available: true,
    pharmacy_available: true,
    diagnostic_available: true,
    operation_theatre_count: 10,
    ventilator_count: 20,
    oxygen_beds: 110,
    specialities: ['HPB Surgery & Liver Transplant', 'Trauma Resuscitation', 'Pulmonology'],
    services: ['24x7 Multi-Organ Emergency', 'Advanced Telemetry', 'Blood Bank'],
    opening_time: '00:00',
    closing_time: '23:59',
    emergency_24x7: true,
    admin_name: 'Dr. Alok Khullar',
    admin_phone: '+91 98408 88770',
    status: 'Approved',
    created_at: '2025-02-20T10:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    hospital_id: 'HOSP-8',
    registration_id: 'REG-HOSP-CMC-0008',
    hospital_name: 'Christian Medical College (CMC) Trauma Center',
    hospital_type: 'Trust',
    registration_number: 'HSP-REG-CMC-008',
    contact_number: '+91 416 228 1000',
    email: 'directorate@cmcvellore.ac.in',
    website: 'https://cmch-vellore.edu',
    address: 'Ida Scudder Road',
    city: 'Vellore',
    district: 'Vellore',
    state: 'Tamil Nadu',
    pincode: '632004',
    latitude: 12.9250,
    longitude: 79.1350,
    total_beds: 750,
    available_beds: 110,
    icu_beds: 60,
    icu_available: 14,
    emergency_beds: 24,
    emergency_available: 8,
    general_beds: 520,
    private_beds: 146,
    ambulance_count: 12,
    blood_bank_available: true,
    pharmacy_available: true,
    diagnostic_available: true,
    operation_theatre_count: 22,
    ventilator_count: 45,
    oxygen_beds: 280,
    specialities: ['Trauma Surgery', 'Intensive Care Unit', 'Hyperbaric Medicine', 'Blood Bank', 'Neurosurgery'],
    services: ['24x7 Apex Emergency', 'Autonomous Blood Bank', 'Disaster Relief Unit'],
    opening_time: '00:00',
    closing_time: '23:59',
    emergency_24x7: true,
    admin_name: 'Dr. Vikram Mathews',
    admin_phone: '+91 94432 11000',
    status: 'Approved',
    created_at: '2025-01-10T10:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  }
];

const seedRegistrations = [
  {
    registration_id: 'REG-PAT-RAJESH-9824',
    auth_user_id: 'user-patient-rajesh',
    name: 'Rajesh V. Sharma',
    email: 'rajesh.sharma@ekavach.health',
    phone: '+91 98401 22819',
    role: 'patient',
    status: 'ACTIVE',
    created_at: '2025-01-10T08:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    registration_id: 'REG-DOC-KAVITHA-4491',
    auth_user_id: 'user-doctor-kavitha',
    name: 'Dr. Kavitha Menon',
    email: 'dr.kavitha@apollo.health',
    phone: '+91 98401 99420',
    role: 'doctor',
    status: 'ACTIVE',
    created_at: '2025-01-12T09:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    registration_id: 'REG-DOC-ARVIND-3829',
    auth_user_id: 'user-doctor-arvind',
    name: 'Dr. Arvind Swaminathan',
    email: 'dr.arvind@aiims.edu',
    phone: '+91 98112 44301',
    role: 'doctor',
    status: 'ACTIVE',
    created_at: '2025-01-12T09:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    registration_id: 'REG-DOC-SHALINI-5120',
    auth_user_id: 'user-doctor-shalini',
    name: 'Dr. Shalini Deshmukh',
    email: 'dr.shalini@manipal.health',
    phone: '+91 98801 77210',
    role: 'doctor',
    status: 'ACTIVE',
    created_at: '2025-01-12T09:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    registration_id: 'REG-DOC-NAIR-4190',
    auth_user_id: 'user-doctor-rajeshnair',
    name: 'Dr. Rajesh K. Nair',
    email: 'dr.rajesh@fortis.health',
    phone: '+91 98440 33890',
    role: 'doctor',
    status: 'ACTIVE',
    created_at: '2025-01-12T09:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    registration_id: 'REG-DOC-PRIYA-6041',
    auth_user_id: 'user-doctor-priya',
    name: 'Dr. Priya R. Sundaram',
    email: 'dr.priya@apollo.health',
    phone: '+91 98402 11980',
    role: 'doctor',
    status: 'ACTIVE',
    created_at: '2025-01-12T09:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    registration_id: 'REG-DOC-ZAID-4771',
    auth_user_id: 'user-doctor-zaid',
    name: 'Dr. Mohammed Zaid',
    email: 'dr.zaid@aiims.edu',
    phone: '+91 98119 55602',
    role: 'doctor',
    status: 'ACTIVE',
    created_at: '2025-01-12T09:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  },
  {
    registration_id: 'REG-ADM-NAMBIAR-0842',
    auth_user_id: 'user-admin-nambiar',
    name: 'Dr. R. K. Nambiar',
    email: 'admin.nambiar@apollo.health',
    phone: '+91 98401 84200',
    role: 'hospital',
    status: 'ACTIVE',
    created_at: '2025-01-10T08:00:00.000Z',
    updated_at: '2026-03-24T12:00:00.000Z'
  }
];

const seedUsers = [
  {
    id: 'user-patient-rajesh',
    registration_id: 'REG-PAT-RAJESH-9824',
    email: 'rajesh.sharma@ekavach.health',
    phone: '+91 98401 22819',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'patient',
    status: 'ACTIVE'
  },
  {
    id: 'user-doctor-kavitha',
    registration_id: 'REG-DOC-KAVITHA-4491',
    email: 'dr.kavitha@apollo.health',
    phone: '+91 98401 99420',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'doctor',
    status: 'ACTIVE'
  },
  {
    id: 'user-doctor-arvind',
    registration_id: 'REG-DOC-ARVIND-3829',
    email: 'dr.arvind@aiims.edu',
    phone: '+91 98112 44301',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'doctor',
    status: 'ACTIVE'
  },
  {
    id: 'user-doctor-shalini',
    registration_id: 'REG-DOC-SHALINI-5120',
    email: 'dr.shalini@manipal.health',
    phone: '+91 98801 77210',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'doctor',
    status: 'ACTIVE'
  },
  {
    id: 'user-doctor-rajeshnair',
    registration_id: 'REG-DOC-NAIR-4190',
    email: 'dr.rajesh@fortis.health',
    phone: '+91 98440 33890',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'doctor',
    status: 'ACTIVE'
  },
  {
    id: 'user-doctor-priya',
    registration_id: 'REG-DOC-PRIYA-6041',
    email: 'dr.priya@apollo.health',
    phone: '+91 98402 11980',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'doctor',
    status: 'ACTIVE'
  },
  {
    id: 'user-doctor-zaid',
    registration_id: 'REG-DOC-ZAID-4771',
    email: 'dr.zaid@aiims.edu',
    phone: '+91 98119 55602',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'doctor',
    status: 'ACTIVE'
  },
  {
    id: 'user-admin-nambiar',
    registration_id: 'REG-ADM-NAMBIAR-0842',
    email: 'admin.nambiar@apollo.health',
    phone: '+91 98401 84200',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'hospital',
    status: 'ACTIVE'
  },
  {
    id: 'user-admin-naman',
    registration_id: 'REG-ADM-NAMAN-0001',
    email: 'namanjain82670@gmail.com',
    phone: '+91 98000 00001',
    passwordHash: DEFAULT_PASSWORD_HASH,
    role: 'hospital',
    status: 'ACTIVE'
  }
];

const seedPatientProfiles = [
  {
    id: 'patient-rajesh',
    userId: 'user-patient-rajesh',
    registration_id: 'REG-PAT-RAJESH-9824',
    registrationId: 'REG-PAT-RAJESH-9824',
    name: 'Rajesh V. Sharma',
    abhaNumber: '9824-8819-3320-TN',
    bloodGroup: 'O+ (Rh Pos)',
    gender: 'Male',
    dob: new Date('1972-06-15'),
    chronicConditions: ['Type II Diabetes (Insulin Dependent)', 'Mild Hypertension'],
    allergies: ['Penicillin (Severe anaphylaxis)'],
    implants: ['Coronary Stent (DES - 2021)'],
    emergencyContacts: [
      { name: 'Ananya S.', relation: 'Spouse', phone: '+91 98401 22819', priority: 1, verified: true },
      { name: 'Dr. Vivek Sharma', relation: 'Brother / Physician', phone: '+91 94440 88129', priority: 2, verified: true }
    ],
    emergencyToken: 'EK-TR-88190-V4',
    qrPayload: 'EKAVACH:ABHA:9824-8819-3320-TN:BLOOD:O_POS:ALLERGY:PENICILLIN:TOKEN:EK-TR-88190-V4',
    hospitalAffiliation: 'Apollo Greams Trauma Hub',
    tag: 'Verified Health ID'
  }
];

const seedDoctorProfiles = [
  {
    id: 'doctor-kavitha',
    userId: 'user-doctor-kavitha',
    registration_id: 'REG-DOC-KAVITHA-4491',
    registrationId: 'REG-DOC-KAVITHA-4491',
    hospitalRegistrationId: 'REG-HOSP-APOLLO-0842',
    name: 'Dr. Kavitha Menon',
    title: 'Chief Interventional Cardio',
    nmcNumber: 'MD-44912-TN',
    specialization: 'Interventional Cardiology & Electrophysiology',
    credentialStatus: 'VERIFIED',
    hospitalAffiliation: 'Apollo Greams Trauma Hub',
    department: 'Cardiology',
    tag: 'ID-9942',
    degrees: 'MD, DM, FACC',
    experienceYears: 18,
    consultationFee: 800,
    availableSlots: ['09:30 AM', '11:00 AM', '02:30 PM', '04:00 PM', '05:30 PM']
  },
  {
    id: 'doctor-arvind',
    userId: 'user-doctor-arvind',
    registration_id: 'REG-DOC-ARVIND-3829',
    registrationId: 'REG-DOC-ARVIND-3829',
    hospitalRegistrationId: 'REG-HOSP-AIIMS-1001',
    name: 'Dr. Arvind Swaminathan',
    title: 'Lead Neurosurgeon & Stroke Specialist',
    nmcNumber: 'MD-38291-DL',
    specialization: 'Neurosurgery & Cerebrovascular Trauma',
    credentialStatus: 'VERIFIED',
    hospitalAffiliation: 'AIIMS New Delhi Trauma Center',
    department: 'Neurology',
    tag: 'ID-8821',
    degrees: 'MS, MCh (Neurosurgery), FINR',
    experienceYears: 15,
    consultationFee: 1000,
    availableSlots: ['10:00 AM', '11:30 AM', '03:00 PM', '04:30 PM']
  },
  {
    id: 'doctor-shalini',
    userId: 'user-doctor-shalini',
    registration_id: 'REG-DOC-SHALINI-5120',
    registrationId: 'REG-DOC-SHALINI-5120',
    hospitalRegistrationId: 'REG-HOSP-MANIPAL-0004',
    name: 'Dr. Shalini Deshmukh',
    title: 'Senior Pulmonologist & Critical Care',
    nmcNumber: 'MD-51204-KA',
    specialization: 'Pulmonary Medicine, ARDS & Bronchoscopy',
    credentialStatus: 'VERIFIED',
    hospitalAffiliation: 'Manipal Hospital Old Airport Road',
    department: 'Pulmonology',
    tag: 'ID-7714',
    degrees: 'MD, DNB (Resp Diseases), FCCP',
    experienceYears: 12,
    consultationFee: 750,
    availableSlots: ['09:00 AM', '10:30 AM', '01:30 PM', '03:30 PM', '05:00 PM']
  },
  {
    id: 'doctor-rajeshnair',
    userId: 'user-doctor-rajeshnair',
    registration_id: 'REG-DOC-NAIR-4190',
    registrationId: 'REG-DOC-NAIR-4190',
    hospitalRegistrationId: 'REG-HOSP-FORTIS-0002',
    name: 'Dr. Rajesh K. Nair',
    title: 'Chief Orthopedic Trauma Surgeon',
    nmcNumber: 'MD-41908-TN',
    specialization: 'Orthopedics, Joint Reconstruction & Polytrauma',
    credentialStatus: 'VERIFIED',
    hospitalAffiliation: 'Fortis Malar Hospital',
    department: 'Orthopedics',
    tag: 'ID-6602',
    degrees: 'MS (Ortho), DNB, FRCS (Tr & Orth)',
    experienceYears: 20,
    consultationFee: 850,
    availableSlots: ['10:00 AM', '12:00 PM', '02:00 PM', '04:00 PM']
  },
  {
    id: 'doctor-priya',
    userId: 'user-doctor-priya',
    registration_id: 'REG-DOC-PRIYA-6041',
    registrationId: 'REG-DOC-PRIYA-6041',
    hospitalRegistrationId: 'REG-HOSP-APOLLO-0842',
    name: 'Dr. Priya R. Sundaram',
    title: 'Consultant Emergency Medicine',
    nmcNumber: 'MD-60419-TN',
    specialization: 'Emergency Medicine & Golden Hour Resuscitation',
    credentialStatus: 'VERIFIED',
    hospitalAffiliation: 'Apollo Greams Trauma Hub',
    department: 'Emergency Medicine',
    tag: 'ID-5519',
    degrees: 'MD (Emergency Medicine), MRCEM',
    experienceYears: 9,
    consultationFee: 600,
    availableSlots: ['09:00 AM', '11:00 AM', '01:00 PM', '03:00 PM', '06:00 PM']
  },
  {
    id: 'doctor-zaid',
    userId: 'user-doctor-zaid',
    registration_id: 'REG-DOC-ZAID-4771',
    registrationId: 'REG-DOC-ZAID-4771',
    hospitalRegistrationId: 'REG-HOSP-AIIMS-1001',
    name: 'Dr. Mohammed Zaid',
    title: 'Director of Nephrology & Renal Transplant',
    nmcNumber: 'MD-47712-DL',
    specialization: 'Nephrology, Dialysis & Renal Transplantation',
    credentialStatus: 'VERIFIED',
    hospitalAffiliation: 'AIIMS New Delhi Trauma Center',
    department: 'Nephrology',
    tag: 'ID-4420',
    degrees: 'MD, DM (Nephrology), FISN',
    experienceYears: 16,
    consultationFee: 900,
    availableSlots: ['11:00 AM', '12:30 PM', '03:30 PM', '05:00 PM']
  }
];

const seedHospitalAdminProfiles = [
  {
    id: 'admin-nambiar',
    userId: 'user-admin-nambiar',
    registration_id: 'REG-ADM-NAMBIAR-0842',
    registrationId: 'REG-ADM-NAMBIAR-0842',
    hospitalId: 'hosp-apollo-greams',
    hospitalRegistrationId: 'REG-HOSP-APOLLO-0842',
    name: 'Dr. R. K. Nambiar',
    title: 'Hospital Administrator',
    designation: 'Chief Medical Officer & Hospital Administrator',
    tag: 'VERIFIED ADMIN'
  },
  {
    id: 'admin-naman',
    userId: 'user-admin-naman',
    registration_id: 'REG-ADM-NAMAN-0001',
    registrationId: 'REG-ADM-NAMAN-0001',
    hospitalId: 'hosp-apollo-greams',
    hospitalRegistrationId: 'REG-HOSP-APOLLO-0842',
    name: 'Naman Jain',
    title: 'System Super Administrator',
    designation: 'National Health Grid Super Administrator',
    tag: 'SUPER ADMIN'
  }
];

const seedEmergencyPass = [
  {
    id: 'pass-rajesh',
    patientProfileId: 'patient-rajesh',
    passToken: 'EK-TR-88190-V4',
    bloodGroup: 'O+ (Rh Pos)',
    criticalAllergies: 'Severe Penicillin anaphylaxis reaction.',
    chronicConditions: 'Type II Diabetes (Insulin Dependent), Mild Hypertension',
    implants: 'Coronary Stent (DES - 2021)',
    iceContacts: [
      { name: 'Ananya S.', relation: 'Spouse', phone: '+91 98401 22819', priority: 1 },
      { name: 'Dr. Vivek Sharma', relation: 'Brother / Physician', phone: '+91 94440 88129', priority: 2 }
    ],
    status: 'ACTIVE',
    qrMatrix: 'data:image/svg+xml;utf8,<svg ...></svg>'
  }
];

const seedAbhaAccounts = [
  {
    id: 'abha-rajesh',
    patientProfileId: 'patient-rajesh',
    abhaNumber: '9824-8819-3320-TN',
    phrAddress: 'rajesh.sharma@abdm',
    linkedMobile: '+91 98401 22819',
    aadhaarRef: 'XXXX-XXXX-4819',
    qrPayload: 'ABDM:PHR:rajesh.sharma@abdm:ABHA:9824-8819-3320-TN',
    verificationStatus: 'LEVEL-4 CERTIFIED',
    issueDate: new Date('2023-01-10')
  }
];

const seedGovernmentSchemes = [
  {
    id: 'scheme-pmjay',
    name: 'Ayushman Bharat PM-JAY',
    code: 'PMJAY',
    description: 'National Health Protection Scheme providing cashless coverage up to ₹5,00,000 per family per year for secondary and tertiary care.',
    coverageAmount: 500000.00,
    department: 'National Health Authority (NHA)',
    eligibilityRules: { seccCategory: 'D1-D7', incomeLimit: 250000 }
  },
  {
    id: 'scheme-cmchis',
    name: 'Chief Minister Comprehensive Health Insurance Scheme (CMCHIS)',
    code: 'CMCHIS',
    description: 'Tamil Nadu State health assurance cover up to ₹5,00,000 for critical surgeries and trauma procedures.',
    coverageAmount: 500000.00,
    department: 'Govt of Tamil Nadu Dept of Health',
    eligibilityRules: { stateResident: true, rationCardRequired: true }
  },
  {
    id: 'scheme-esi',
    name: 'Employees State Insurance Scheme',
    code: 'ESI',
    description: 'Full medical care and disability protection for insured formal sector employees and dependents.',
    coverageAmount: 1000000.00,
    department: 'Ministry of Labour & Employment',
    eligibilityRules: { wageThreshold: 21000 }
  }
];

const seedSchemeEnrollments = [
  {
    id: 'enrollment-rajesh-pmjay',
    patientProfileId: 'patient-rajesh',
    schemeId: 'scheme-pmjay',
    status: 'RENEWAL_DUE',
    policyNumber: 'PMJAY-TN-2024-991204',
    claimHistory: [
      { date: '2025-11-14', hospital: 'Apollo Greams', procedure: 'Cardiac Angiogram & Stenting', amountClaimed: 185000, status: 'APPROVED' }
    ]
  },
  {
    id: 'enrollment-rajesh-cmchis',
    patientProfileId: 'patient-rajesh',
    schemeId: 'scheme-cmchis',
    status: 'ENROLLED',
    policyNumber: 'CMCHIS-CHE-882190',
    claimHistory: []
  }
];

const seedBeds = [
  { id: 'bed-icu', hospitalId: 'hosp-apollo-greams', wardType: 'ICU', wardName: 'Intensive Coronary Care Unit', totalBeds: 50, occupiedBeds: 46, availableBeds: 4, status: 'HIGH_LOAD' },
  { id: 'bed-ccu', hospitalId: 'hosp-apollo-greams', wardType: 'CCU', wardName: 'Critical Care Unit', totalBeds: 32, occupiedBeds: 28, availableBeds: 4, status: 'HIGH_LOAD' },
  { id: 'bed-trauma', hospitalId: 'hosp-apollo-greams', wardType: 'TRAUMA_BAY', wardName: 'Emergency Trauma Bays', totalBeds: 8, occupiedBeds: 6, availableBeds: 2, status: 'OPERATIONAL' },
  { id: 'bed-general', hospitalId: 'hosp-apollo-greams', wardType: 'GENERAL', wardName: 'Inpatient General & Special Wards', totalBeds: 360, occupiedBeds: 302, availableBeds: 58, status: 'OPERATIONAL' }
];

const seedTriageEntries = [
  {
    id: 'triage-1',
    patientProfileId: 'patient-rajesh',
    hospitalId: 'hosp-apollo-greams',
    assignedDoctorId: 'doctor-kavitha',
    triageColor: 'RED',
    priorityLevel: 'Priority 1 (Critical)',
    bayNumber: 'Bay 02',
    patientName: 'Rajesh V. Sharma',
    abhaNumber: '9824-8819-3320-TN',
    arrivalTime: new Date(Date.now() - 15 * 60 * 1000),
    vitals: { heartRate: '112 bpm', bp: '190/115', spO2: '88%', respRate: '24 /min' },
    condition: 'Acute Myocardial Infarction • ST Elevation',
    status: 'ATTENDING'
  },
  {
    id: 'triage-2',
    patientProfileId: null,
    hospitalId: 'hosp-apollo-greams',
    assignedDoctorId: null,
    triageColor: 'YELLOW',
    priorityLevel: 'Priority 2 (Urgent)',
    bayNumber: 'Bay 04',
    patientName: 'Meenakshi Sundaram',
    abhaNumber: '7712-4401-TN',
    arrivalTime: new Date(Date.now() - 32 * 60 * 1000),
    vitals: { heartRate: '84 bpm', bp: '135/85', spO2: '97%', respRate: '18 /min' },
    condition: 'Polytrauma / Right Femur Compound Fracture',
    status: 'INGRESS'
  },
  {
    id: 'triage-3',
    patientProfileId: null,
    hospitalId: 'hosp-apollo-greams',
    assignedDoctorId: null,
    triageColor: 'GREEN',
    priorityLevel: 'Priority 3 (Stable)',
    bayNumber: 'Bay 06',
    patientName: 'Harish K. Varma',
    abhaNumber: '4402-9918-TN',
    arrivalTime: new Date(Date.now() - 55 * 60 * 1000),
    vitals: { heartRate: '72 bpm', bp: '120/80', spO2: '99%', respRate: '16 /min' },
    condition: 'Deep Forearm Laceration / Suture In Progress',
    status: 'INGRESS'
  }
];

const seedStaffMembers = [
  { id: 'ST-1042', hospitalId: 'hosp-apollo-greams', initials: 'PR', name: 'Priya R.', role: 'Critical Care Nurse', department: 'ICU', status: 'ON_DUTY', extension: 'Ext. 4102 • Shift A' },
  { id: 'ST-2189', hospitalId: 'hosp-apollo-greams', initials: 'KM', name: 'Karthik M.', role: 'Radiology & CT Specialist', department: 'Diagnostic Bay', status: 'ON_DUTY', extension: 'Ext. 2219 • Shift A' },
  { id: 'ST-3401', hospitalId: 'hosp-apollo-greams', initials: 'DS', name: 'Deepa S.', role: 'Trauma Triage Nurse', department: 'ER Bay', status: 'OFF_DUTY', extension: 'Ext. 1104 • Shift C' },
  { id: 'ST-4820', hospitalId: 'hosp-apollo-greams', initials: 'RA', name: 'Rajeshwari Ananthan', role: 'Senior OT Technician', department: 'Surgical Wing', status: 'ON_DUTY', extension: 'Ext. 3381 • Shift A' },
  { id: 'ST-5091', hospitalId: 'hosp-apollo-greams', initials: 'AK', name: 'Anand Kumar', role: 'Clinical Pharmacist', department: 'Pharmacy', status: 'ON_DUTY', extension: 'Ext. 5509 • Shift A' },
  { id: 'ST-6124', hospitalId: 'hosp-apollo-greams', initials: 'SD', name: 'Sunita Deshmukh', role: 'Inpatient Head Nurse', department: 'General Ward', status: 'OFF_DUTY', extension: 'Ext. 4201 • Shift B' },
  { id: 'ST-7730', hospitalId: 'hosp-apollo-greams', initials: 'BV', name: 'Balaji Venkatesh', role: 'Biomedical Equipment Engineer', department: 'ICU & Telemetry', status: 'ON_DUTY', extension: 'Ext. 6112 • On Call' },
  { id: 'ST-8812', hospitalId: 'hosp-apollo-greams', initials: 'MN', name: 'Meera Namboodiri', role: 'Pediatric Care Assistant', department: 'NICU / PICU', status: 'ON_DUTY', extension: 'Ext. 4810 • Shift A' }
];

const seedPharmacyItems = [
  { id: 'pharm-1', hospitalId: 'hosp-apollo-greams', name: 'Metformin 500mg', genericName: 'Generic: Metformin Hydrochloride • Oral Tablet', category: 'Diabetes', lotNumber: 'Lot #MT-8819', storageLocation: 'Main Dispensary (Rack B-04)', stockQty: 4200, unit: 'units', reorderThreshold: 1000, status: 'IN_STOCK', icon: 'pill' },
  { id: 'pharm-2', hospitalId: 'hosp-apollo-greams', name: 'Epinephrine 1mg/mL', genericName: 'Emergency Crash-Cart Reserve • 1:1000 IV', category: 'Emergency Resuscitation', lotNumber: 'Lot #EP-4401', storageLocation: 'ER Bay 1-3 & Trauma Crash Cart', stockQty: 320, unit: 'Amps', reorderThreshold: 150, status: 'IN_STOCK', icon: 'vaccines' },
  { id: 'pharm-3', hospitalId: 'hosp-apollo-greams', name: 'Cefotaxime 1g IV', genericName: 'Broad-spectrum Cephalosporin Antibiotic', category: 'Antibiotics', lotNumber: 'Lot #CF-9921', storageLocation: 'Inpatient Central Stock', stockQty: 42, unit: 'Vials', reorderThreshold: 100, status: 'LOW_STOCK', icon: 'science' },
  { id: 'pharm-4', hospitalId: 'hosp-apollo-greams', name: 'Rosuvastatin 10mg', genericName: 'Lipid-lowering HMG-CoA Reductase Inhibitor', category: 'Cardiovascular', lotNumber: 'Lot #RS-2041', storageLocation: 'Main Dispensary (Rack C-02)', stockQty: 1800, unit: 'units', reorderThreshold: 500, status: 'IN_STOCK', icon: 'pill' },
  { id: 'pharm-5', hospitalId: 'hosp-apollo-greams', name: 'Aspirin 75mg Gastro-Resistant', genericName: 'Antiplatelet Platelet Aggregation Inhibitor', category: 'Cardiovascular', lotNumber: 'Lot #AS-7718', storageLocation: 'Main Dispensary (Rack C-03)', stockQty: 2400, unit: 'units', reorderThreshold: 500, status: 'IN_STOCK', icon: 'pill' },
  { id: 'pharm-6', hospitalId: 'hosp-apollo-greams', name: 'Insulin Glargine 100 IU/mL', genericName: 'Long-Acting Basal Recombinant Insulin Soln', category: 'Diabetes', lotNumber: 'Lot #IN-8891', storageLocation: 'Cold Vault 4°C (Unit 2)', stockQty: 110, unit: 'Pens', reorderThreshold: 50, status: 'IN_STOCK', icon: 'vaccines' }
];

const seedNetworkNodes = [
  { id: 'HOSP-1', name: 'AIIMS New Delhi Trauma Center', subtext: 'Apex National Super-Specialty Center • ABDM Tier-1 Node', location: 'Ansari Nagar, New Delhi', subloc: 'National Central Hub • PIN 110029', icuBeds: 14, wardBeds: 42, specialties: 'Polytrauma, Neurotrauma, Hyperbaric O2', status: 'connected', region: 'national', distanceKm: 2180.0, o2ReserveHours: 120, bloodBankUnits: 450, latencySec: 0.08, icon: 'local_hospital' },
  { id: 'HOSP-2', name: 'Fortis Malar Hospital', subtext: 'Super-Specialty Trauma & Critical Care Unit', location: 'Adyar, Chennai, Tamil Nadu', subloc: 'South Chennai Node • 4.8 km away', icuBeds: 8, wardBeds: 22, specialties: 'Cardiothoracic, ECMO Support, Burns', status: 'connected', region: 'chennai south', distanceKm: 4.8, o2ReserveHours: 84, bloodBankUnits: 120, latencySec: 0.02, icon: 'domain' },
  { id: 'HOSP-3', name: 'Stanley Medical College & Hospital', subtext: 'Government Medical College & State Trauma Center', location: 'Royapuram, Chennai, Tamil Nadu', subloc: 'North Chennai Node • 8.2 km away', icuBeds: 19, wardBeds: 60, specialties: 'Micro-Reconstructive, Toxicological Emergency', status: 'connected', region: 'chennai', distanceKm: 8.2, o2ReserveHours: 96, bloodBankUnits: 210, latencySec: 0.03, icon: 'emergency' },
  { id: 'HOSP-4', name: 'Manipal Hospital Old Airport Road', subtext: 'Tertiary Multi-Specialty & Organ Transplant Center', location: 'Bengaluru, Karnataka', subloc: 'Inter-State Corridor Node • 290 km', icuBeds: 11, wardBeds: 34, specialties: 'Organ Retrieval, Interventional Radiology', status: 'connected', region: 'south', distanceKm: 290.0, o2ReserveHours: 104, bloodBankUnits: 340, latencySec: 0.05, icon: 'domain' }
];

const seedAppointments = [
  {
    id: 'apt-1',
    tokenNumber: 'EK-SLOT-101',
    patientProfileId: 'patient-rajesh',
    doctorProfileId: 'doctor-kavitha',
    hospitalId: 'hosp-apollo-greams',
    patientName: 'Rajesh V. Sharma',
    patientPhone: '+91 98401 22819',
    timeSlot: '10:30 AM',
    scheduledAt: new Date(Date.now() + 24 * 60 * 60 * 1000), // Tomorrow 10:30 AM
    mode: 'IN_PERSON',
    status: 'CONFIRMED',
    department: 'Cardiology',
    symptoms: 'Follow-up on coronary stent evaluation and HbA1c review.',
    notes: JSON.stringify({
      serviceType: 'DOCTOR_CONSULT',
      bookingFor: 'SELF',
      relation: 'Self',
      patientAge: '52',
      patientGender: 'Male',
      userNotes: 'Please bring latest fasting glucose reports.'
    })
  },
  {
    id: 'apt-2',
    tokenNumber: 'EK-SLOT-102',
    patientProfileId: 'patient-rajesh',
    doctorProfileId: 'doctor-kavitha',
    hospitalId: 'hosp-apollo-greams',
    patientName: 'Venkatesh Sharma',
    patientPhone: '+91 98401 22819',
    timeSlot: '11:45 AM',
    scheduledAt: new Date(Date.now() + 48 * 60 * 60 * 1000),
    mode: 'IN_PERSON',
    status: 'PENDING',
    department: 'Cardiology',
    symptoms: 'Echocardiography & Lipid Workup for elderly family member',
    notes: JSON.stringify({
      serviceType: 'DIAGNOSTIC_TEST',
      bookingFor: 'OTHER',
      relation: 'Father',
      testName: 'Echocardiography & Lipid Profile',
      patientAge: '76',
      patientGender: 'Male',
      userNotes: 'Senior citizen wheelchair assistance requested at gate.'
    })
  }
];

const seedMedicalRecords = [
  {
    id: 'rec-1',
    patientProfileId: 'patient-rajesh',
    uploadedByUserId: 'user-doctor-kavitha',
    title: 'Comprehensive Metabolic Panel & HbA1c',
    recordType: 'LAB_REPORT',
    fileUrl: '/uploads/hba1c_report_rajesh.pdf',
    date: new Date('2026-10-18'),
    notes: 'HbA1c: 6.8%, Fasting Blood Sugar: 124 mg/dL. Creatinine: 0.9 mg/dL.'
  },
  {
    id: 'rec-2',
    patientProfileId: 'patient-rajesh',
    uploadedByUserId: 'user-doctor-kavitha',
    title: 'Cardiology Discharge Summary & Stent Protocol',
    recordType: 'DISCHARGE_SUMMARY',
    fileUrl: '/uploads/cardio_discharge_rajesh.pdf',
    date: new Date('2025-11-16'),
    notes: 'Drug-eluting stent successfully deployed in LAD. Patient stable on DAPT.'
  }
];

const seedConsentGrants = [
  {
    id: 'consent-kavitha',
    patientProfileId: 'patient-rajesh',
    grantedToDoctorId: 'doctor-kavitha',
    recordScope: 'ALL',
    status: 'ACTIVE',
    grantedAt: new Date('2024-01-01')
  }
];

const seedAccessLogs = [
  {
    id: 'log-1',
    patientProfileId: 'patient-rajesh',
    accessorUserId: 'user-doctor-kavitha',
    accessorRole: 'doctor',
    accessorName: 'Dr. Kavitha Menon',
    hospitalId: 'hosp-apollo-greams',
    accessType: 'CONSULTATION_VIEW',
    reason: 'Pre-consultation cardiac record review',
    ipAddress: '10.14.22.84',
    userAgent: 'Apollo-Greams-Workstation-ChromeOS',
    latencyMs: 18,
    timestamp: new Date(Date.now() - 3 * 3600 * 1000)
  },
  {
    id: 'log-2',
    patientProfileId: 'patient-rajesh',
    accessorUserId: 'user-doctor-kavitha',
    accessorRole: 'doctor',
    accessorName: 'Dr. Kavitha Menon',
    hospitalId: 'hosp-apollo-greams',
    accessType: 'EMERGENCY_PASS_BYPASS',
    reason: 'ER Bay 3 Emergency Triage Ingress Protocol',
    ipAddress: '10.14.22.90',
    userAgent: 'Apollo-ER-Bay3-Scanner',
    latencyMs: 12,
    timestamp: new Date(Date.now() - 24 * 3600 * 1000)
  }
];

module.exports = {
  seedRegistrations,
  seedHospitals,
  seedUsers,
  seedPatientProfiles,
  seedDoctorProfiles,
  seedHospitalAdminProfiles,
  seedEmergencyPass,
  seedAbhaAccounts,
  seedGovernmentSchemes,
  seedSchemeEnrollments,
  seedBeds,
  seedTriageEntries,
  seedStaffMembers,
  seedPharmacyItems,
  seedNetworkNodes,
  seedAppointments,
  seedMedicalRecords,
  seedConsentGrants,
  seedAccessLogs,
  HOSPITAL_SCHEMA_FIELDS,
  seedHospitalSchemaRecords,
};
